name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambda  # Set working directory to your Lambda folder
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: './lambda/requirements/dev.txt'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Run Tests with Coverage
        run: |
          python -m pytest -v --cov=src --cov-report=xml

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          fail_ci_if_error: true

  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambda
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: './lambda/requirements/dev.txt'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
          # Install additional linting tools
          pip install black flake8 mypy

      - name: Run Black
        run: |
          black --check src tests

      - name: Run Flake8
        run: |
          flake8 src tests

      - name: Run mypy
        run: |
          mypy src tests

  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./lambda
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy Lambda Function
        run: |
          bash deploy.sh

